// Builds the shipped plateau ladder (decision 0011, issue #18): for each of
// the 150 ladder levels, searches (layout, seed) pairs until the generated
// deal's difficulty score lands in the level's band window, then writes
// data/ladder.json (the shipped seeds) and data/ladder-report.md (the
// per-level band/score/spike report the PM signs off against).
//
// Deterministic: the search order is a pure function of the level number, so
// re-running the script reproduces the same ladder byte-for-byte. Builds to
// core/dist/build-ladder.js.
//
// Usage: node dist/build-ladder.js

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

import { assessDifficulty } from './src/difficulty.js';
import { generateValidatedLevel } from './src/generator.js';
import { bandForLevel, LADDER_LENGTH, LADDER_WINDOWS } from './src/ladder.js';
import type { LadderEntry } from './src/ladder.js';
import { parseLayout } from './src/layouts.js';
import type { LayoutFile } from './src/layouts.js';

const LAYOUT_DIR = new URL('../../data/layouts/', import.meta.url);
const LADDER_FILE = new URL('../../data/ladder.json', import.meta.url);
const REPORT_FILE = new URL('../../data/ladder-report.md', import.meta.url);

const SEEDS_PER_LAYOUT = 200;

const layouts: LayoutFile[] = readdirSync(LAYOUT_DIR)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((f) => parseLayout(JSON.parse(readFileSync(new URL(f, LAYOUT_DIR), 'utf8'))));

interface BuiltLevel extends LadderEntry {
  readonly band: string;
  readonly spike: boolean;
  readonly score: number;
}

/**
 * Find a (layout, seed) whose score fits the level's window. Layout rotation
 * starts at a level-dependent offset so consecutive levels vary visually even
 * when several layouts can serve the same band.
 */
function buildLevel(level: number): BuiltLevel {
  const { band, spike } = bandForLevel(level);
  const window = LADDER_WINDOWS[band];
  for (let l = 0; l < layouts.length; l++) {
    const layout = layouts[(level + l) % layouts.length]!;
    for (let s = 0; s < SEEDS_PER_LAYOUT; s++) {
      const seed = level * 100_000 + s;
      const generated = generateValidatedLevel(layout, seed);
      const { score } = assessDifficulty(generated);
      if (score >= window.min && score < window.max) {
        // Store the seed that validated (generateValidatedLevel may reseed).
        return { level, layoutId: layout.id, seed: generated.seed, band, spike, score };
      }
    }
  }
  throw new Error(`level ${level}: no (layout, seed) hit the ${band} window after full search`);
}

const built: BuiltLevel[] = [];
for (let level = 1; level <= LADDER_LENGTH; level++) {
  built.push(buildLevel(level));
  if (level % 10 === 0) console.log(`built ${level}/${LADDER_LENGTH}`);
}

const ladder: LadderEntry[] = built.map(({ level, layoutId, seed }) => ({ level, layoutId, seed }));
writeFileSync(LADDER_FILE, JSON.stringify(ladder, null, 2) + '\n');

const rows = built
  .map(
    (b) =>
      `| ${b.level} | ${b.band}${b.spike ? ' **(spike)**' : ''} | ${b.layoutId} | ${b.seed} | ${b.score.toFixed(4)} |`,
  )
  .join('\n');
writeFileSync(
  REPORT_FILE,
  `# Ladder report — plateau ladder (decision 0011, issue #18)

Generated by \`core/build-ladder.ts\`. ${LADDER_LENGTH} levels; bands are score
windows over \`difficultyScore\` (see \`core/src/ladder.ts\`). PM sign-off
target per issue #18 acceptance criteria.

| Level | Band | Layout | Seed | Score |
|---|---|---|---|---|
${rows}
`,
);
console.log(`wrote ${LADDER_LENGTH} levels to data/ladder.json and data/ladder-report.md`);
